--------------------------------------------------------------------------------
-- INFORMATION                                                                --
--------------------------------------------------------------------------------

-- Generate GNU makefile from Lua root description

--------------------------------------------------------------------------------
-- MODULE                                                                     --
--------------------------------------------------------------------------------

local Runtime = require("com.runtime")
local Model   = require("make-model")

local format = string.format
local gsub   = string.gsub
local concat = table.concat
local append = table.insert
local stderr = io.stderr

local writefile   = Runtime.writefile
local newpathname = Runtime.newpathname

--------------------------------------------------------------------------------
-- PRIVATE FUNCTIONS                                                          --
--------------------------------------------------------------------------------

local function GEN_NativePathname (Model, InternalPathname)
  return gsub(InternalPathname, "/", Model.HostSeparator)
end

local function GEN_EmitHeader (Model, Lines)
  -- Retrieve data
  local Triples = Model.Triples
  -- Headers
  append(Lines, "# FILE GENERATED BY make-generate.lua")
  append(Lines, format("# Source %s", Model.RootFile))
  append(Lines, format("#   Host %s", Model.HostOS))
  for Index = 1, #Triples do
    append(Lines, format("# Triple %s", Triples[Index]))
  end
  append(Lines, "")
  -- Collect environment names for EXPORT
  local Names = {}
  for Name in pairs(Model.Environment) do
    append(Names, Name)
  end
  table.sort(Names)
  -- Generate the exports
  for Index, Name in ipairs(Names) do
    local ExportLine = format("export %s = %s", Name, Model.Environment[Name])
    append(Lines, ExportLine)
  end
  -- Add a blank line after the exports
  if (#Names > 0) then
    append(Lines, "")
  end
end

local function GEN_EmitDirMarkerRule (Model, Lines)
  append(Lines, format("%s%s%s:", "%", Model.HostSeparator, Model.MarkerName))
  if (Model.HostOS == "windows") then
    append(Lines, "\tif not exist $* mkdir $*")
    append(Lines, "\ttype NUL > $@")
  else
    append(Lines, "\tmkdir -p $*")
    append(Lines, "\ttouch $@")
  end
  append(Lines, "")
end

local function GEN_Prerequisites (Model, Rule)
  -- Retrieve data
  local Prerequisites = Rule.Prerequisites
  local Items         = {}
  -- Convert each prerequisite to HOST separator \ or /
  for Index, Prerequisite in ipairs(Prerequisites) do
    local NativePrerequisite = GEN_NativePathname(Model, Prerequisite)
    append(Items, NativePrerequisite)
  end
  -- Adds "dir/auto-dir-ok" as last prerequisite for auto directory creation
  local OutputDir = Rule.OutDir
  if (OutputDir ~= "") then
    local NativeOutputDir    = GEN_NativePathname(Model, OutputDir)
    local MarkerPrerequisite = format("%s%s%s", NativeOutputDir, Model.HostSeparator, Model.MarkerName)
    append(Items, MarkerPrerequisite)
  end
  -- Merge into a single string
  local PrerequisitesString = concat(Items, " ")
  return PrerequisitesString
end

local function GEN_EmitRule (Model, Lines, Rule)
  -- Prepare
  local MainOut       = Rule.Outs[1]
  local TargetName    = GEN_NativePathname(Model, MainOut)
  local LeftPart      = format("%s:", TargetName)
  local Prerequisites = GEN_Prerequisites(Model, Rule)
  local RuleLine
  if (Prerequisites == "") then
    RuleLine = format("%s:", TargetName)
  else
    RuleLine = format("%s: %s", TargetName, Prerequisites)
  end
  -- Add the lines
  append(Lines, RuleLine)
  for Index, RunLine in ipairs(Rule.RunLines) do
    local IndentedLine = format("\t%s", RunLine)
    append(Lines, IndentedLine)
  end
end

--------------------------------------------------------------------------------
-- PUBLIC FUNCTIONS                                                           --
--------------------------------------------------------------------------------

local function GEN_Generate (Model)
  -- local data
  local Lines = {}
  -- Header
  GEN_EmitHeader(Model, Lines)
  append(Lines, ".PHONY: clean all")
  append(Lines, "")
  -- First target is "all"
  local AllNames = {}
  for Index, Artifact in ipairs(Model.Artifacts) do
    local NativeArtifact = GEN_NativePathname(Model, Artifact)
    append(AllNames, NativeArtifact)
  end
  append(Lines, format("all: %s", concat(AllNames, " ")))
  append(Lines, "")
  -- Directory Marker rule
  GEN_EmitDirMarkerRule(Model, Lines)
  -- All the rules
  for Index, Rule in ipairs(Model.Rules) do
    GEN_EmitRule(Model, Lines, Rule)
    append(Lines, "")
  end
  -- Clean rule
  append(Lines, "clean:")
  for Index, CleanCommand in ipairs(Model.CleanCommands) do
    append(Lines, format("\t%s", CleanCommand))
  end
  return concat(Lines, "\n")
end

--------------------------------------------------------------------------------
-- MAIN                                                                       --
--------------------------------------------------------------------------------

local USAGE = [[usage: lua55ce tools/lua/make-generate.lua <root-description> [options]
options:
  --output <name>       Output filename (optional)
  --host <arch-os-libc> Target host (optional, default: current host)

examples: --host x86_64-linux-musl
]]

local EXIT_SUCCESS = 0
local EXIT_ERROR   = 1

local function GEN_Usage ()
  stderr:write(USAGE)
  os.exit(EXIT_ERROR)
end

local function GEN_FatalError (ErrorString)
  stderr:write(format("%s\n",ErrorString))
  GEN_Usage()
end

local function GEN_ParseArguments (Arguments)
  local NewOptions = {
    Output   = false,
    Host     = false,
    RootFile = false,
  }
  local Index = 1
  while (Index <= #Arguments) do
    local Entry = Arguments[Index]
    if (Entry == "--output") then
      Index = (Index + 1)
      NewOptions.Output = Arguments[Index]
      assert(NewOptions.Output, "--output requires a filename")
    elseif (Entry == "--host") then
      Index = (Index + 1)
      local HostTriple = Arguments[Index]
      assert(HostTriple, "--host requires a target triple (like x86_64-linux-musl)")
      NewOptions.Host = HostTriple
    elseif (not NewOptions.RootFile) then
      NewOptions.RootFile = Entry
    end
    Index = (Index + 1)
  end
  return NewOptions
end

--------------------------------------------------------------------------------
-- MAIN                                                                       --
--------------------------------------------------------------------------------

local Options = GEN_ParseArguments(arg)

if (not Options.RootFile) then
  GEN_FatalError()
end

local MakeModel  = Model.Build(Options.RootFile, Options.Host)
local OutputName = Options.Output

-- No flag "--output" was given, choose a default name
if (not OutputName) then
  local BaseName = gsub(Options.RootFile, "%.lua$", "")
  OutputName = format("%s-makefile-%s", BaseName, MakeModel.HostTriple)
end

local OutputDir = newpathname(OutputName):getdirectory("native")

if (OutputDir ~= "") then
  Runtime.makedirectory(OutputDir)
end

local MakefileContents = GEN_Generate(MakeModel)

local Success, ErrorString = writefile(OutputName, MakefileContents)
if (not Success) then
  error(format("cannot write %s: %s", OutputName, ErrorString))
end

os.exit(EXIT_SUCCESS)
