--------------------------------------------------------------------------------
-- Generated by ComEXE ffi-compiler at 2026-05-24T07:22:31                    --
-- tiny-libc.h                                                                --
--------------------------------------------------------------------------------

local libffi = require("com.ffi")

--------------------------------------------------------------------------------
-- FUNCTIONS                                                                  --
--------------------------------------------------------------------------------

local function Bind (Library)
  -- Functions
  Library.free = Library:bind(libffi.void, "free", libffi.pointer)
  Library.malloc = Library:bind(libffi.pointer, "malloc", libffi.uint64)
  Library.puts = Library:bind(libffi.sint32, "puts", libffi.pointer)
  Library.qsort = Library:bind(libffi.void, "qsort", libffi.pointer, libffi.uint64, libffi.uint64, libffi.pointer)
  Library.sprintf = Library:variadicbind(libffi.sint32, "sprintf", libffi.pointer, libffi.pointer)
end

--------------------------------------------------------------------------------
-- PUBLIC API                                                                 --
--------------------------------------------------------------------------------

local PUBLIC_API = {
  bind = Bind,
}

return PUBLIC_API