--------------------------------------------------------------------------------
-- Generated by ComEXE ffi-compiler at 2026-05-30T09:08:45                    --
-- tiny-sqlite3.h                                                             --
--------------------------------------------------------------------------------

local libffi = require("com.ffi")

--------------------------------------------------------------------------------
-- FUNCTIONS                                                                  --
--------------------------------------------------------------------------------

local function Bind (Library)
  -- Constants
  Library.SQLITE_BLOB = 4
  Library.SQLITE_DONE = 101
  Library.SQLITE_FLOAT = 2
  Library.SQLITE_INTEGER = 1
  Library.SQLITE_NULL = 5
  Library.SQLITE_OK = 0
  Library.SQLITE_ROW = 100
  Library.SQLITE_TEXT = 3
  -- Functions
  Library.sqlite3_bind_blob = Library:bind(libffi.sint32, "sqlite3_bind_blob", libffi.pointer, libffi.sint32, libffi.pointer, libffi.sint32, libffi.pointer)
  Library.sqlite3_bind_double = Library:bind(libffi.sint32, "sqlite3_bind_double", libffi.pointer, libffi.sint32, libffi.double)
  Library.sqlite3_bind_int64 = Library:bind(libffi.sint32, "sqlite3_bind_int64", libffi.pointer, libffi.sint32, libffi.sint64)
  Library.sqlite3_bind_null = Library:bind(libffi.sint32, "sqlite3_bind_null", libffi.pointer, libffi.sint32)
  Library.sqlite3_bind_text = Library:bind(libffi.sint32, "sqlite3_bind_text", libffi.pointer, libffi.sint32, libffi.pointer, libffi.sint32, libffi.pointer)
  Library.sqlite3_changes = Library:bind(libffi.sint32, "sqlite3_changes", libffi.pointer)
  Library.sqlite3_close = Library:bind(libffi.sint32, "sqlite3_close", libffi.pointer)
  Library.sqlite3_column_blob = Library:bind(libffi.pointer, "sqlite3_column_blob", libffi.pointer, libffi.sint32)
  Library.sqlite3_column_bytes = Library:bind(libffi.sint32, "sqlite3_column_bytes", libffi.pointer, libffi.sint32)
  Library.sqlite3_column_count = Library:bind(libffi.sint32, "sqlite3_column_count", libffi.pointer)
  Library.sqlite3_column_double = Library:bind(libffi.double, "sqlite3_column_double", libffi.pointer, libffi.sint32)
  Library.sqlite3_column_int64 = Library:bind(libffi.sint64, "sqlite3_column_int64", libffi.pointer, libffi.sint32)
  Library.sqlite3_column_name = Library:bind(libffi.cstring, "sqlite3_column_name", libffi.pointer, libffi.sint32)
  Library.sqlite3_column_text = Library:bind(libffi.cstring, "sqlite3_column_text", libffi.pointer, libffi.sint32)
  Library.sqlite3_column_type = Library:bind(libffi.sint32, "sqlite3_column_type", libffi.pointer, libffi.sint32)
  Library.sqlite3_errmsg = Library:bind(libffi.cstring, "sqlite3_errmsg", libffi.pointer)
  Library.sqlite3_exec = Library:bind(libffi.sint32, "sqlite3_exec", libffi.pointer, libffi.pointer, libffi.pointer, libffi.pointer, libffi.pointer)
  Library.sqlite3_finalize = Library:bind(libffi.sint32, "sqlite3_finalize", libffi.pointer)
  Library.sqlite3_last_insert_rowid = Library:bind(libffi.sint64, "sqlite3_last_insert_rowid", libffi.pointer)
  Library.sqlite3_open = Library:bind(libffi.sint32, "sqlite3_open", libffi.pointer, libffi.pointer)
  Library.sqlite3_prepare_v2 = Library:bind(libffi.sint32, "sqlite3_prepare_v2", libffi.pointer, libffi.pointer, libffi.sint32, libffi.pointer, libffi.pointer)
  Library.sqlite3_reset = Library:bind(libffi.sint32, "sqlite3_reset", libffi.pointer)
  Library.sqlite3_step = Library:bind(libffi.sint32, "sqlite3_step", libffi.pointer)
end

--------------------------------------------------------------------------------
-- PUBLIC API                                                                 --
--------------------------------------------------------------------------------

local PUBLIC_API = {
  bind = Bind,
}

return PUBLIC_API