--------------------------------------------------------------------------------
-- Generated by ComEXE ffi-compiler at 2026-06-07T05:44:45                    --
-- tiny-win32.h                                                               --
--------------------------------------------------------------------------------

local libffi = require("com.ffi")

--------------------------------------------------------------------------------
-- FUNCTIONS                                                                  --
--------------------------------------------------------------------------------

local function Bind (Library)
  -- Constants
  Library.ANTIALIASED_QUALITY = 4
  Library.COLOR_WINDOW = 5
  Library.CP_UTF8 = 65001
  Library.CS_HREDRAW = 2
  Library.CS_OWNDC = 32
  Library.CS_VREDRAW = 1
  Library.CW_USEDEFAULT = 2147483648
  Library.DEFAULT_CHARSET = 1
  Library.DEFAULT_PITCH = 0
  Library.DT_CALCRECT = 1024
  Library.DT_CENTER = 1
  Library.DT_SINGLELINE = 32
  Library.DT_VCENTER = 4
  Library.FF_SWISS = 32
  Library.FW_NORMAL = 400
  Library.IDC_ARROW = 32512
  Library.IDI_APPLICATION = 32512
  Library.LTGRAY_BRUSH = 1
  Library.SPI_GETNONCLIENTMETRICS = 41
  Library.SW_SHOWDEFAULT = 10
  Library.TRANSPARENT = 1
  Library.WM_COMMAND = 273
  Library.WM_DESTROY = 2
  Library.WM_PAINT = 15
  Library.WM_QUIT = 18
  Library.WM_SIZE = 5
  Library.WM_TIMER = 275
  Library.WS_CHILD = 1073741824
  Library.WS_CLIPCHILDREN = 33554432
  Library.WS_EX_CLIENTEDGE = 512
  Library.WS_OVERLAPPEDWINDOW = 13565952
  Library.WS_VISIBLE = 268435456
  -- Structures
  Library.LOGFONTA = libffi.newstructure("LOGFONTA",
    libffi.sint32, "lfHeight",
    libffi.sint32, "lfWidth",
    libffi.sint32, "lfEscapement",
    libffi.sint32, "lfOrientation",
    libffi.sint32, "lfWeight",
    libffi.uint8, "lfItalic",
    libffi.uint8, "lfUnderline",
    libffi.uint8, "lfStrikeOut",
    libffi.uint8, "lfCharSet",
    libffi.uint8, "lfOutPrecision",
    libffi.uint8, "lfClipPrecision",
    libffi.uint8, "lfQuality",
    libffi.uint8, "lfPitchAndFamily",
    libffi.pointer, "lfFaceName"
  )
  Library.NONCLIENTMETRICSA = libffi.newstructure("NONCLIENTMETRICSA",
    libffi.uint32, "cbSize",
    libffi.sint32, "iBorderWidth",
    libffi.sint32, "iScrollWidth",
    libffi.sint32, "iScrollHeight",
    libffi.sint32, "iCaptionWidth",
    libffi.sint32, "iCaptionHeight",
    Library.LOGFONTA, "lfCaptionFont",
    libffi.sint32, "iSmCaptionWidth",
    libffi.sint32, "iSmCaptionHeight",
    Library.LOGFONTA, "lfSmCaptionFont",
    libffi.sint32, "iMenuWidth",
    libffi.sint32, "iMenuHeight",
    Library.LOGFONTA, "lfMenuFont",
    Library.LOGFONTA, "lfStatusFont",
    Library.LOGFONTA, "lfMessageFont"
  )
  Library.POINT = libffi.newstructure("POINT",
    libffi.sint32, "x",
    libffi.sint32, "y"
  )
  Library.RECT = libffi.newstructure("RECT",
    libffi.sint32, "left",
    libffi.sint32, "top",
    libffi.sint32, "right",
    libffi.sint32, "bottom"
  )
  Library.WNDCLASSEX = libffi.newstructure("WNDCLASSEX",
    libffi.uint32, "cbSize",
    libffi.uint32, "style",
    libffi.pointer, "lpfnWndProc",
    libffi.sint32, "cbClsExtra",
    libffi.sint32, "cbWndExtra",
    libffi.pointer, "hInstance",
    libffi.pointer, "hIcon",
    libffi.pointer, "hCursor",
    libffi.pointer, "hbrBackground",
    libffi.cstring, "lpszMenuName",
    libffi.cstring, "lpszClassName",
    libffi.pointer, "hIconSm"
  )
  Library.MSG = libffi.newstructure("MSG",
    libffi.pointer, "hwnd",
    libffi.uint32, "message",
    libffi.uint64, "wParam",
    libffi.sint64, "lParam",
    libffi.uint32, "time",
    Library.POINT, "pt",
    libffi.uint32, "lPrivate"
  )
  Library.PAINTSTRUCT = libffi.newstructure("PAINTSTRUCT",
    libffi.pointer, "hdc",
    libffi.sint32, "fErase",
    Library.RECT, "rcPaint",
    libffi.sint32, "fRestore",
    libffi.sint32, "fIncUpdate",
    libffi.uint64, "reservedA",
    libffi.uint64, "reservedB",
    libffi.uint64, "reservedC",
    libffi.uint64, "reservedD"
  )
  -- Functions
  Library.BeginPaint = Library:bind(libffi.pointer, "BeginPaint", libffi.pointer, libffi.pointer)
  Library.CreateFontA = Library:bind(libffi.pointer, "CreateFontA", libffi.sint32, libffi.sint32, libffi.sint32, libffi.sint32, libffi.sint32, libffi.uint32, libffi.uint32, libffi.uint32, libffi.uint32, libffi.uint32, libffi.uint32, libffi.uint32, libffi.uint32, libffi.pointer)
  Library.CreateFontIndirectA = Library:bind(libffi.pointer, "CreateFontIndirectA", libffi.pointer)
  Library.CreateWindowExA = Library:bind(libffi.pointer, "CreateWindowExA", libffi.uint32, libffi.pointer, libffi.pointer, libffi.uint32, libffi.sint32, libffi.sint32, libffi.sint32, libffi.sint32, libffi.pointer, libffi.pointer, libffi.pointer, libffi.pointer)
  Library.DefWindowProcA = Library:bind(libffi.sint64, "DefWindowProcA", libffi.pointer, libffi.uint32, libffi.uint64, libffi.sint64)
  Library.DeleteObject = Library:bind(libffi.sint32, "DeleteObject", libffi.pointer)
  Library.DispatchMessageA = Library:bind(libffi.sint64, "DispatchMessageA", libffi.pointer)
  Library.DrawTextW = Library:bind(libffi.sint32, "DrawTextW", libffi.pointer, libffi.pointer, libffi.sint32, libffi.pointer, libffi.uint32)
  Library.EndPaint = Library:bind(libffi.sint32, "EndPaint", libffi.pointer, libffi.pointer)
  Library.FillRect = Library:bind(libffi.sint32, "FillRect", libffi.pointer, libffi.pointer, libffi.pointer)
  Library.GetClientRect = Library:bind(libffi.sint32, "GetClientRect", libffi.pointer, libffi.pointer)
  Library.GetDC = Library:bind(libffi.pointer, "GetDC", libffi.pointer)
  Library.GetMessageA = Library:bind(libffi.sint32, "GetMessageA", libffi.pointer, libffi.pointer, libffi.uint32, libffi.uint32)
  Library.GetModuleHandleA = Library:bind(libffi.pointer, "GetModuleHandleA", libffi.pointer)
  Library.GetStockObject = Library:bind(libffi.pointer, "GetStockObject", libffi.sint32)
  Library.InvalidateRect = Library:bind(libffi.sint32, "InvalidateRect", libffi.pointer, libffi.pointer, libffi.sint32)
  Library.KillTimer = Library:bind(libffi.sint32, "KillTimer", libffi.pointer, libffi.uint64)
  Library.LoadCursorA = Library:bind(libffi.pointer, "LoadCursorA", libffi.pointer, libffi.pointer)
  Library.LoadIconA = Library:bind(libffi.pointer, "LoadIconA", libffi.pointer, libffi.pointer)
  Library.MoveWindow = Library:bind(libffi.sint32, "MoveWindow", libffi.pointer, libffi.sint32, libffi.sint32, libffi.sint32, libffi.sint32, libffi.sint32)
  Library.MultiByteToWideChar = Library:bind(libffi.sint32, "MultiByteToWideChar", libffi.uint32, libffi.uint32, libffi.pointer, libffi.sint32, libffi.pointer, libffi.sint32)
  Library.PostQuitMessage = Library:bind(libffi.void, "PostQuitMessage", libffi.sint32)
  Library.RegisterClassExA = Library:bind(libffi.uint16, "RegisterClassExA", libffi.pointer)
  Library.ReleaseDC = Library:bind(libffi.sint32, "ReleaseDC", libffi.pointer, libffi.pointer)
  Library.SelectObject = Library:bind(libffi.pointer, "SelectObject", libffi.pointer, libffi.pointer)
  Library.SetBkMode = Library:bind(libffi.sint32, "SetBkMode", libffi.pointer, libffi.sint32)
  Library.SetTimer = Library:bind(libffi.uint64, "SetTimer", libffi.pointer, libffi.uint64, libffi.uint32, libffi.pointer)
  Library.ShowWindow = Library:bind(libffi.sint32, "ShowWindow", libffi.pointer, libffi.sint32)
  Library.SystemParametersInfoA = Library:bind(libffi.sint32, "SystemParametersInfoA", libffi.uint32, libffi.uint32, libffi.pointer, libffi.uint32)
  Library.TranslateMessage = Library:bind(libffi.sint32, "TranslateMessage", libffi.pointer)
  Library.UpdateWindow = Library:bind(libffi.sint32, "UpdateWindow", libffi.pointer)
end

--------------------------------------------------------------------------------
-- PUBLIC API                                                                 --
--------------------------------------------------------------------------------

local PUBLIC_API = {
  bind = Bind,
}

return PUBLIC_API