/*----------------------------------------------------------------------------*
 * PROJECT  ComEXE                                                            *
 * FILENAME lua-libminizip-ng.c                                               *
 * CONTENT  Raw Lua bindings for minizip-ng                                   *
 *----------------------------------------------------------------------------*
 * Copyright (c) 2020-2026 Pascal COMBIER                                     *
 * This source code is licensed under the BSD 2-clause license found in the   *
 * LICENSE file in the root directory of this source tree.                    *
 *----------------------------------------------------------------------------*
 *
 * Note that the implementation below currently does not involve mimalloc
 */

/*============================================================================*/
/* MAKEHEADERS PUBLIC INTERFACE                                               */
/*============================================================================*/

#if MKH_INTERFACE

/*---------*/
/* HEADERS */
/*---------*/

/* luaopen_minizipng generated by makeheaders, rely on the type lua_State */
#include <lua.h>

#endif

/*============================================================================*/
/* IMPLEMENTATION HEADERS                                                     */
/*============================================================================*/

#include <stdint.h>  /* int32_t  */
#include <stdlib.h>  /* malloc   */
#include <lauxlib.h> /* luaL_Reg */

/* minizip-ng headers, order is important */
#include <mz.h>
#include <mz_os.h>
#include <mz_strm_os.h>
#include <mz_zip.h>

/* zlib constants */
#include <zlib.h>

/*============================================================================*/
/* MZ_ZIP_FILE                                                                */
/*============================================================================*/

/* Returns the handle or nil */
static int MZ_ZipFileCreate (lua_State *LuaState)
{
  mz_zip_file *FileInfo = calloc(1, sizeof(mz_zip_file));

  if (FileInfo == NULL)
  {
    lua_pushnil(LuaState);
  }
  else
  {
    lua_pushlightuserdata(LuaState, FileInfo);
  }

  return 1; /* Number of values returned on the stack */
}

static int MZ_ZipFileDelete (lua_State *LuaState)
{
  void *FileInfo = lua_touserdata(LuaState, 1);

  free(FileInfo);

  return 0; /* Number of values returned on the stack */
}

/* WARNING: the string must remain referenced on the Lua side until the entry is
 * closed */
static int MZ_ZipFileSetFilename (lua_State *LuaState)
{
  mz_zip_file *FileInfo = lua_touserdata(LuaState, 1);

  FileInfo->filename = lua_tostring(LuaState, 2);

  return 0; /* Number of values returned on the stack */
}

static int MZ_ZipFileSetModifiedDate (lua_State *LuaState)
{
  mz_zip_file *FileInfo = lua_touserdata(LuaState, 1);

  FileInfo->modified_date = luaL_checkinteger(LuaState, 2);

  return 0; /* Number of values returned on the stack */
}

static int MZ_ZipFileSetVersionMadeby (lua_State *LuaState)
{
  mz_zip_file *FileInfo = lua_touserdata(LuaState, 1);

  FileInfo->version_madeby = luaL_checkinteger(LuaState, 2);

  return 0; /* Number of values returned on the stack */
}

static int MZ_ZipFileSetFlag (lua_State *LuaState)
{
  mz_zip_file *FileInfo = lua_touserdata(LuaState, 1);

  FileInfo->flag = luaL_checkinteger(LuaState, 2);

  return 0; /* Number of values returned on the stack */
}

static int MZ_ZipFileSetCompressionMethod (lua_State *LuaState)
{
  mz_zip_file *FileInfo = lua_touserdata(LuaState, 1);

  FileInfo->compression_method = luaL_checkinteger(LuaState, 2);

  return 0; /* Number of values returned on the stack */
}

static int MZ_ZipFileSetExternalFa (lua_State *LuaState)
{
  mz_zip_file *FileInfo = lua_touserdata(LuaState, 1);

  FileInfo->external_fa = luaL_checkinteger(LuaState, 2);

  return 0; /* Number of values returned on the stack */
}

/* Push nil if FileInfo->filename is NULL */
static int MZ_ZipFileGetFilename (lua_State *LuaState)
{
  mz_zip_file *FileInfo = lua_touserdata(LuaState, 1);

  lua_pushstring(LuaState, FileInfo->filename);

  return 1; /* Number of values returned on the stack */
}

static int MZ_ZipFileGetUncompressedSize (lua_State *LuaState)
{
  mz_zip_file *FileInfo = lua_touserdata(LuaState, 1);

  lua_pushinteger(LuaState, FileInfo->uncompressed_size);

  return 1; /* Number of values returned on the stack */
}

/*============================================================================*/
/* STREAM OPERATIONS                                                          */
/*============================================================================*/

/* Returns the handle, or nil */
static int MZ_StreamOsCreate (lua_State *LuaState)
{
  void *Stream = mz_stream_os_create();

  if (Stream == NULL)
  {
    lua_pushnil(LuaState);
  }
  else
  {
    lua_pushlightuserdata(LuaState, Stream);
  }

  return 1; /* Number of values returned on the stack */
}

static int MZ_StreamOsOpen (lua_State *LuaState)
{
  void       *Stream = lua_touserdata(LuaState, 1);
  const char *Path   = luaL_checkstring(LuaState, 2);
  int32_t     Mode   = luaL_checkinteger(LuaState, 3);
  int32_t     Result = mz_stream_os_open(Stream, Path, Mode);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

static int MZ_StreamOsClose (lua_State *LuaState)
{
  void    *Stream = lua_touserdata(LuaState, 1);
  int32_t  Result = mz_stream_os_close(Stream);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

/* Obviously make the Lua reference become invalid */
static int MZ_StreamOsDelete (lua_State *LuaState)
{
  void *Stream = lua_touserdata(LuaState, 1);

  mz_stream_os_delete(&Stream);

  return 0; /* Number of values returned on the stack */
}

/*============================================================================*/
/* ZIP OPERATIONS                                                             */
/*============================================================================*/

/* Returns the handle, or nil */
static int MZ_ZipCreate (lua_State *LuaState)
{
  void *ZipHandle = mz_zip_create();

  if (ZipHandle == NULL)
  {
    lua_pushnil(LuaState);
  }
  else
  {
    lua_pushlightuserdata(LuaState, ZipHandle);
  }

  return 1; /* Number of values returned on the stack */
}

/* Obviously make the given Lua reference invalid */
static int MZ_ZipDelete (lua_State *LuaState)
{
  void *ZipHandle = lua_touserdata(LuaState, 1);

  mz_zip_delete(&ZipHandle);

  return 0; /* Number of values returned on the stack */
}

static int MZ_ZipOpen (lua_State *LuaState)
{
  void    *ZipHandle = lua_touserdata(LuaState, 1);
  void    *Stream    = lua_touserdata(LuaState, 2);
  int32_t  Mode      = luaL_checkinteger(LuaState, 3);
  int32_t  Result    = mz_zip_open(ZipHandle, Stream, Mode);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

static int MZ_ZipClose (lua_State *LuaState)
{
  void    *ZipHandle = lua_touserdata(LuaState, 1);
  int32_t  Result    = mz_zip_close(ZipHandle);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

static int MZ_ZipSetComment (lua_State *LuaState)
{
  void       *ZipHandle = lua_touserdata(LuaState, 1);
  const char *Comment   = luaL_checkstring(LuaState, 2);
  int32_t     Result    = mz_zip_set_comment(ZipHandle, Comment);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

static int MZ_ZipSetVersionMadeby (lua_State *LuaState)
{
  void     *ZipHandle = lua_touserdata(LuaState, 1);
  uint16_t  MadeBy    = luaL_checkinteger(LuaState, 2);
  int32_t   Result    = mz_zip_set_version_madeby(ZipHandle, MadeBy);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

static int MZ_ZipSetDataDescriptor (lua_State *LuaState)
{
  void    *ZipHandle = lua_touserdata(LuaState, 1);
  uint8_t  Enabled   = lua_toboolean(LuaState, 2);
  int32_t  Result    = mz_zip_set_data_descriptor(ZipHandle, Enabled);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

/*============================================================================*/
/* ZIP WRITE OPERATIONS                                                       */
/*============================================================================*/

/* Note that with current build MZ_ZIP_NO_CRYPTO and MZ_ZIP_NO_ENCRYPTION are
 * disabled, using them will return MZ_SUPPORT_ERROR
 *
 * Raw is the same thing as MZ_COMPRESS_METHOD_STORE
 */
static int MZ_ZipEntryWriteOpen (lua_State *LuaState)
{
  void        *ZipHandle = lua_touserdata(LuaState, 1);
  mz_zip_file *FileInfo  = lua_touserdata(LuaState, 2);
  int16_t      Level     = luaL_checkinteger(LuaState, 3);
  uint8_t      Raw       = lua_toboolean(LuaState, 4);
  const char  *Password  = lua_tostring(LuaState, 5);

  int32_t Result = mz_zip_entry_write_open(ZipHandle, FileInfo, Level, Raw, Password);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

/* Note: mz_zip_entry_write limits entry to 2 GiB (int32_t) */
static int MZ_ZipEntryWrite (lua_State *LuaState)
{
  size_t Length;
  
  void       *ZipHandle = lua_touserdata(LuaState, 1);
  const char *Buffer    = luaL_checklstring(LuaState, 2, &Length);
  int32_t     Result    = mz_zip_entry_write(ZipHandle, Buffer, Length);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

static int MZ_ZipEntryClose (lua_State *LuaState)
{
  void    *ZipHandle = lua_touserdata(LuaState, 1);
  int32_t  Result    = mz_zip_entry_close(ZipHandle);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

/*============================================================================*/
/* ZIP READ OPERATIONS                                                        */
/*============================================================================*/

static int MZ_ZipGotoFirstEntry (lua_State *LuaState)
{
  void    *ZipHandle = lua_touserdata(LuaState, 1);
  int32_t  Result    = mz_zip_goto_first_entry(ZipHandle);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

static int MZ_ZipGotoNextEntry (lua_State *LuaState)
{
  void    *ZipHandle = lua_touserdata(LuaState, 1);
  int32_t  Result    = mz_zip_goto_next_entry(ZipHandle);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

static int MZ_ZipLocateEntry (lua_State *LuaState)
{
  void       *ZipHandle  = lua_touserdata(LuaState, 1);
  const char *Filename   = luaL_checkstring(LuaState, 2);
  uint8_t     IgnoreCase = lua_toboolean(LuaState, 3);
  int32_t     Result     = mz_zip_locate_entry(ZipHandle, Filename, IgnoreCase);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

/* The returned handle stays valid until the entry cursor moves (goto_next_entry
 * or locate_entry).
 */
static int MZ_ZipEntryGetInfo (lua_State *LuaState)
{
  void        *ZipHandle = lua_touserdata(LuaState, 1);
  mz_zip_file *FileInfo  = NULL;
  int32_t      Result    = mz_zip_entry_get_info(ZipHandle, &FileInfo);

  if ((Result == MZ_OK) && (FileInfo != NULL))
  {
    lua_pushlightuserdata(LuaState, FileInfo);
    lua_pushnil(LuaState);
  }
  else
  {
    lua_pushnil(LuaState);
    lua_pushinteger(LuaState, Result);
  }

  return 2; /* Number of values returned on the stack */
}

/* Returns MZ_OK when the current entry is a directory */
static int MZ_ZipEntryIsDir (lua_State *LuaState)
{
  void    *ZipHandle = lua_touserdata(LuaState, 1);
  int32_t  Result    = mz_zip_entry_is_dir(ZipHandle);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

/* Note that with current build MZ_ZIP_NO_CRYPTO and MZ_ZIP_NO_ENCRYPTION are
 * disabled, using them will return MZ_SUPPORT_ERROR
 *
 * Raw is the same thing as MZ_COMPRESS_METHOD_STORE
 */
static int MZ_ZipEntryReadOpen (lua_State *LuaState)
{
  void       *ZipHandle = lua_touserdata(LuaState, 1);
  uint8_t     Raw       = lua_toboolean(LuaState, 2);
  const char *Password  = lua_tostring(LuaState, 3);
  int32_t     Result    = mz_zip_entry_read_open(ZipHandle, Raw, Password);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

/* Provided buffer capacity must be >= SizeInBytes */
static int MZ_ZipEntryRead (lua_State *LuaState)
{
  void    *ZipHandle   = lua_touserdata(LuaState, 1);
  void    *Buffer      = lua_touserdata(LuaState, 2);
  int32_t  SizeInBytes = luaL_checkinteger(LuaState, 3);
  int32_t  Result      = mz_zip_entry_read(ZipHandle, Buffer, SizeInBytes);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

/* The 3 NULL are output pointers, unused here */
static int MZ_ZipEntryReadClose (lua_State *LuaState)
{
  void    *ZipHandle = lua_touserdata(LuaState, 1);
  int32_t  Result    = mz_zip_entry_read_close(ZipHandle, NULL, NULL, NULL);

  lua_pushinteger(LuaState, Result);

  return 1; /* Number of values returned on the stack */
}

/*============================================================================*/
/* PUBLIC API                                                                 */
/*============================================================================*/

static const struct luaL_Reg MINIZIP_FUNCTIONS[] =
{
  /* Zip file descriptor */
  { "mz_zip_file_create",                 MZ_ZipFileCreate               },
  { "mz_zip_file_delete",                 MZ_ZipFileDelete               },
  { "mz_zip_file_set_filename",           MZ_ZipFileSetFilename          },
  { "mz_zip_file_set_modified_date",      MZ_ZipFileSetModifiedDate      },
  { "mz_zip_file_set_version_madeby",     MZ_ZipFileSetVersionMadeby     },
  { "mz_zip_file_set_flag",               MZ_ZipFileSetFlag              },
  { "mz_zip_file_set_compression_method", MZ_ZipFileSetCompressionMethod },
  { "mz_zip_file_set_external_fa",        MZ_ZipFileSetExternalFa        },
  { "mz_zip_file_get_filename",           MZ_ZipFileGetFilename          },
  { "mz_zip_file_get_uncompressed_size",  MZ_ZipFileGetUncompressedSize  },
  /* Stream operations */
  { "mz_stream_os_create",                MZ_StreamOsCreate              },
  { "mz_stream_os_open",                  MZ_StreamOsOpen                },
  { "mz_stream_os_close",                 MZ_StreamOsClose               },
  { "mz_stream_os_delete",                MZ_StreamOsDelete              },
  /* Zip operations */
  { "mz_zip_create",                      MZ_ZipCreate                   },
  { "mz_zip_delete",                      MZ_ZipDelete                   },
  { "mz_zip_open",                        MZ_ZipOpen                     },
  { "mz_zip_close",                       MZ_ZipClose                    },
  { "mz_zip_set_comment",                 MZ_ZipSetComment               },
  { "mz_zip_set_version_madeby",          MZ_ZipSetVersionMadeby         },
  { "mz_zip_set_data_descriptor",         MZ_ZipSetDataDescriptor        },
  /* Zip write operations */
  { "mz_zip_entry_write_open",            MZ_ZipEntryWriteOpen           },
  { "mz_zip_entry_write",                 MZ_ZipEntryWrite               },
  { "mz_zip_entry_close",                 MZ_ZipEntryClose               },
  /* Zip read operations */
  { "mz_zip_goto_first_entry",            MZ_ZipGotoFirstEntry           },
  { "mz_zip_goto_next_entry",             MZ_ZipGotoNextEntry            },
  { "mz_zip_locate_entry",                MZ_ZipLocateEntry              },
  { "mz_zip_entry_get_info",              MZ_ZipEntryGetInfo             },
  { "mz_zip_entry_is_dir",                MZ_ZipEntryIsDir               },
  { "mz_zip_entry_read_open",             MZ_ZipEntryReadOpen            },
  { "mz_zip_entry_read",                  MZ_ZipEntryRead                },
  { "mz_zip_entry_read_close",            MZ_ZipEntryReadClose           },
  /* End of list */
  { NULL, NULL }
};

static void MZ_RegisterConstant (lua_State  *LuaState,
                                 const char *Name,
                                 int         Value)
{
  lua_pushinteger(LuaState, Value);
  lua_setfield(LuaState, -2, Name);
}

static void MZ_RegisterVersionConstants (lua_State *LuaState)
{
  lua_pushstring(LuaState, MZ_VERSION);
  lua_setfield(LuaState, -2, "MZ_VERSION");
  MZ_RegisterConstant(LuaState, "MZ_VERSION_BUILD", MZ_VERSION_BUILD);
}

static void MZ_RegisterErrorConstants (lua_State *LuaState)
{
  MZ_RegisterConstant(LuaState, "MZ_OK",             MZ_OK);
  MZ_RegisterConstant(LuaState, "MZ_STREAM_ERROR",   MZ_STREAM_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_DATA_ERROR",     MZ_DATA_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_MEM_ERROR",      MZ_MEM_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_BUF_ERROR",      MZ_BUF_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_VERSION_ERROR",  MZ_VERSION_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_END_OF_LIST",    MZ_END_OF_LIST);
  MZ_RegisterConstant(LuaState, "MZ_END_OF_STREAM",  MZ_END_OF_STREAM);
  MZ_RegisterConstant(LuaState, "MZ_PARAM_ERROR",    MZ_PARAM_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_FORMAT_ERROR",   MZ_FORMAT_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_INTERNAL_ERROR", MZ_INTERNAL_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_CRC_ERROR",      MZ_CRC_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_CRYPT_ERROR",    MZ_CRYPT_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_EXIST_ERROR",    MZ_EXIST_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_PASSWORD_ERROR", MZ_PASSWORD_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_SUPPORT_ERROR",  MZ_SUPPORT_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_HASH_ERROR",     MZ_HASH_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_OPEN_ERROR",     MZ_OPEN_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_CLOSE_ERROR",    MZ_CLOSE_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_SEEK_ERROR",     MZ_SEEK_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_TELL_ERROR",     MZ_TELL_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_READ_ERROR",     MZ_READ_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_WRITE_ERROR",    MZ_WRITE_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_SIGN_ERROR",     MZ_SIGN_ERROR);
  MZ_RegisterConstant(LuaState, "MZ_SYMLINK_ERROR",  MZ_SYMLINK_ERROR);
}

static void MZ_RegisterOpenModeConstants (lua_State *LuaState)
{
  MZ_RegisterConstant(LuaState, "MZ_OPEN_MODE_READ",      MZ_OPEN_MODE_READ);
  MZ_RegisterConstant(LuaState, "MZ_OPEN_MODE_WRITE",     MZ_OPEN_MODE_WRITE);
  MZ_RegisterConstant(LuaState, "MZ_OPEN_MODE_READWRITE", MZ_OPEN_MODE_READWRITE);
  MZ_RegisterConstant(LuaState, "MZ_OPEN_MODE_APPEND",    MZ_OPEN_MODE_APPEND);
  MZ_RegisterConstant(LuaState, "MZ_OPEN_MODE_CREATE",    MZ_OPEN_MODE_CREATE);
  MZ_RegisterConstant(LuaState, "MZ_OPEN_MODE_EXISTING",  MZ_OPEN_MODE_EXISTING);
  MZ_RegisterConstant(LuaState, "MZ_OPEN_MODE_NOFOLLOW",  MZ_OPEN_MODE_NOFOLLOW);
  MZ_RegisterConstant(LuaState, "MZ_SEEK_SET",            MZ_SEEK_SET);
  MZ_RegisterConstant(LuaState, "MZ_SEEK_CUR",            MZ_SEEK_CUR);
  MZ_RegisterConstant(LuaState, "MZ_SEEK_END",            MZ_SEEK_END);
}

static void MZ_RegisterCompressionConstants (lua_State *LuaState)
{
  MZ_RegisterConstant(LuaState, "MZ_COMPRESS_METHOD_STORE",   MZ_COMPRESS_METHOD_STORE);
  MZ_RegisterConstant(LuaState, "MZ_COMPRESS_METHOD_DEFLATE", MZ_COMPRESS_METHOD_DEFLATE);
  MZ_RegisterConstant(LuaState, "MZ_COMPRESS_LEVEL_DEFAULT",  MZ_COMPRESS_LEVEL_DEFAULT);
  MZ_RegisterConstant(LuaState, "MZ_COMPRESS_LEVEL_FAST",     MZ_COMPRESS_LEVEL_FAST);
  MZ_RegisterConstant(LuaState, "MZ_COMPRESS_LEVEL_NORMAL",   MZ_COMPRESS_LEVEL_NORMAL);
  MZ_RegisterConstant(LuaState, "MZ_COMPRESS_LEVEL_BEST",     MZ_COMPRESS_LEVEL_BEST);
}

static void MZ_RegisterFlagConstants (lua_State *LuaState)
{
  MZ_RegisterConstant(LuaState, "MZ_ZIP_FLAG_DEFLATE_NORMAL",     MZ_ZIP_FLAG_DEFLATE_NORMAL);
  MZ_RegisterConstant(LuaState, "MZ_ZIP_FLAG_DEFLATE_MAX",        MZ_ZIP_FLAG_DEFLATE_MAX);
  MZ_RegisterConstant(LuaState, "MZ_ZIP_FLAG_DEFLATE_FAST",       MZ_ZIP_FLAG_DEFLATE_FAST);
  MZ_RegisterConstant(LuaState, "MZ_ZIP_FLAG_DEFLATE_SUPER_FAST", MZ_ZIP_FLAG_DEFLATE_SUPER_FAST);
  MZ_RegisterConstant(LuaState, "MZ_ZIP_FLAG_DATA_DESCRIPTOR",    MZ_ZIP_FLAG_DATA_DESCRIPTOR);
  MZ_RegisterConstant(LuaState, "MZ_ZIP_FLAG_UTF8",               MZ_ZIP_FLAG_UTF8);
}

static void MZ_RegisterZlibConstants (lua_State *LuaState)
{
  MZ_RegisterConstant(LuaState, "Z_DEFAULT_COMPRESSION", Z_DEFAULT_COMPRESSION);
  MZ_RegisterConstant(LuaState, "Z_NO_COMPRESSION",      Z_NO_COMPRESSION);
  MZ_RegisterConstant(LuaState, "Z_BEST_SPEED",          Z_BEST_SPEED);
  MZ_RegisterConstant(LuaState, "Z_BEST_COMPRESSION",    Z_BEST_COMPRESSION);
  MZ_RegisterConstant(LuaState, "Z_DEFLATED",            Z_DEFLATED);
}

static void MZ_RegisterHostSystemConstants (lua_State *LuaState)
{
  MZ_RegisterConstant(LuaState, "MZ_HOST_SYSTEM_MSDOS",        MZ_HOST_SYSTEM_MSDOS);
  MZ_RegisterConstant(LuaState, "MZ_HOST_SYSTEM_UNIX",         MZ_HOST_SYSTEM_UNIX);
  MZ_RegisterConstant(LuaState, "MZ_HOST_SYSTEM_WINDOWS_NTFS", MZ_HOST_SYSTEM_WINDOWS_NTFS);
  MZ_RegisterConstant(LuaState, "MZ_HOST_SYSTEM_RISCOS",       MZ_HOST_SYSTEM_RISCOS);
  MZ_RegisterConstant(LuaState, "MZ_HOST_SYSTEM_OSX_DARWIN",   MZ_HOST_SYSTEM_OSX_DARWIN);
  MZ_RegisterConstant(LuaState, "MZ_VERSION_MADEBY",           MZ_VERSION_MADEBY);
}

extern int luaopen_minizipng (lua_State *LuaState)
{
  /* Create the table with all functions */
  luaL_newlib(LuaState, MINIZIP_FUNCTIONS);

  /* Register constants */
  MZ_RegisterVersionConstants(LuaState);
  MZ_RegisterErrorConstants(LuaState);
  MZ_RegisterOpenModeConstants(LuaState);
  MZ_RegisterCompressionConstants(LuaState);
  MZ_RegisterZlibConstants(LuaState);
  MZ_RegisterFlagConstants(LuaState);
  MZ_RegisterHostSystemConstants(LuaState);

  return 1; /* Number of values returned on the stack */
}
