on:
  workflow_dispatch:
    inputs:
      version-tag:
        required: true
        type: string

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64-x86-64 musl-tools zip
      - run: chmod +x ./make-all.sh
      - run: chmod +x third-party/src/tcc-vio/bootstrap-on-linux.sh
      - run: chmod +x third-party/src/tcc-vio/src-mini-trunk/configure
      - run: ./make-all.sh
      - run: mv dist/lua55ce.zip dist/lua55ce-${{ inputs.version-tag }}.zip
      - run: dist/lua55ce-x86_64-linux tests/runner.lua --fast
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version-tag }}
          files: dist/lua55ce-${{ inputs.version-tag }}.zip
          draft: true
